site_name: Jacob AWS Certified Big Data Specialty Tutorial
site_description: "Jacob's AWS Certified Big Data Specialty"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxawscbdbook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Section1:Intro':
    - 'AWS Certified Big Data Specialty 2020 - In Depth & Hands On!': 'chap1/1intro.md'
  - 'Section2:Collection':
    - 'L1 Collections - Kinesis DataStream Overview': 'chap2/2Kinesis_data_collection.md'
    - 'L2 [Exercise] Kinesis Firehose (PurchaseLogs/OrderLogs)': 'chap2/3Coll_Kinesis_Firehose_Exer.md'
    - 'L3 [Exercise] Kinesis Data Streams': 'chap2/4Coll_Kinesis_DS_Exer.md'
    - 'L4 SQS vs. Kinesis Data Stream': 'chap2/5Coll_SQS_Kinesis.md'
    - 'L5 IoT Overview and DeepDive': 'chap2/6Coll_IOT.md'
    - 'L6 Data Collection Others': 'chap2/7Coll_Others.md'
    - 'L7 MSK Managed Streaming for Apache Kafka (Amazon MSK)': 'chap2/7Coll_MSK.md'
  - 'Section3:Storage':
    - 'L1 Storage S3': 'chap3/8Storage_S3.md'
    - 'L2 DynamoDB Overview': 'chap3/9Storage_dynamoDB.md'
    - 'L3 Hands on S3': 'chap3/8Hands_onS3.md'
    - 'L4 ElastiCache Overview': 'chap3/10Storage_cache.md'
  - 'Section4:Processing':
    - 'L1 AWS Lambda': 'chap4/11Process_Lambda.md'
    - 'L2 [Exercise] AWS Lambda': 'chap4/12Process_Lambda_Exer.md'
    - 'L3 AWS Glue and Lake Formation': 'chap4/13Process_ETL_intro.md'
    - 'L4 EMR Elastic MapReduce': 'chap4/15process_EMR.md'
    - 'L5 Elastic MapReduce Exercise': 'chap4/17Process_EMR_Exer.md'
    - 'L6 AWS Data Pipeline': 'chap4/15process_DataPipeline.md'
    - 'L7 Deep Learning': 'chap4/20Process_DL.md'
  - 'Section5:Analysis':
    - 'L1 Amazon Kinesis Data Analytics': 'chap5/21Ana_KA.md'
    - 'L2 Kinesis Analytics Exercise': 'chap5/22Ana_Kinesis_ana_Exer.md'
    - 'L3 Amazon Elasticsearch Service': 'chap5/23Ana_ES.md'
    - 'L4 Amazon Elasticsearch Service Exercise': 'chap5/24Ana_ES_Exer.md'
    - 'L5 Amazon Athena': 'chap5/25Ana_Athena.md'
    - 'L6 [Exercise] AWS Glue and Athena': 'chap5/26Glue_Athena_Exer.md'
    - 'L7 AWS Redshift': 'chap5/27Ana_Redshift.md'
    - 'L8 [Exercise] Redshift Spectrum': 'chap5/28Redshift_Spectrum_exer.md'
  - 'Section6:Visualization':
    - 'L1 Visualization': 'chap6/30Vis_Qs.md'
    - 'L2 Amazon Quicksight Exercise': 'chap6/31Vis_Exer.md'
  - 'Section7:Security':
    - 'L1 Security - Encryption': 'chap7/32Secu_Encryption.md'
    - 'L2 AWS Services Security Deep Dive': 'chap7/33Secu_bg_svc.md'
    - 'L3 Account and Identity Federation': 'chap7/34Secu_account_fedration.md'
    - 'L4 Polices, CloudTrail & VPCe': 'chap7/35Secu_others.md'
  - 'Section8:WrapUp':
    - 'L1 AWS Bigdata Integration': 'chap8/36bg_integration.md'
    - 'L2 AWS Big Data Instances': 'chap8/37bg_instances.md'
  - 'Section9:Machine Learning':
    - 'AWS Machine Learning （Amazon ML Service/Amazon SageMaker)': 'chap9/18Process_ML.md'
  - 'Section10:Quizs':
    - 'Quiz1 Collection': 'chap10/qz1_coll.md'
    - 'Quiz2 Storage': 'chap10/qz2_storage.md'
    - 'Quiz3 AWS Lambda': 'chap10/qz3_lambda.md'
    - 'Quiz4 AWS Glue': 'chap10/qz4_glue.md'
    - 'Quiz5 EMR and the Hadoop Ecosystem': 'chap10/qz5_emr.md'
    - 'Quiz6 Kinesis Analytics': 'chap10/qz6_ka.md'
    - 'Quiz7 Amazon ES': 'chap10/qz7_ES.md'
    - 'Quiz8 Amazon Athena': 'chap10/qz8_athena.md'
    - 'Quiz9 Amazon Redshift': 'chap10/qz9_redshift.md'
    - 'Quiz10 Amazon Quicksight': 'chap10/qz10_quicksight.md'
    - 'Quiz11 Security': 'chap10/qz11_security.md'
    - 'Quiz12 Amazon Machine Learning and Sagemaker': 'chap10/qz12_ML.md'
    - 'AWS Certified Data Analytics Specialty Practice Exam': 'chap10/qz_final.md'
  - 'Section11: Learning Big Data':
    - '第一节 大数据体系中明确路径': 'chap11/chap11_1bigdata_intro.md'
    - '第二节 大数据架构 & Hadoop介绍': 'chap11/chap11_2bigdata_structure.md'
    - '第三节 大数据中的数据来源': 'chap11/chap11_3bigdata_coll.md'
    - '第四节 HDFS解决大数据存储问题 & Hadoop on K8S': 'chap11/chap11_4bigdata_hdfs.md'
    - '第五节 HBase 和 Hive': 'chap11/chap11_5bigdata_hive_hbase.md'
    - '第六节 消息系统 Kafka 与 Flume': 'chap11/chap11_6bigdtat_kafka_flume.md'
    - '第七节 MapReduce 处理大数据': 'chap11/chap11_7bigdata_mapreduce.md'
    - '第八节 Spark 与 Flink 的爱恨情仇 (Spark)': 'chap11/chap11_8bigdata_spark.md'
    - '第九节 Spark 与 Flink 的爱恨情仇 (Flink)': 'chap11/chap11_9bigdata_flink.md'
  - 'Section12: AWS Big Data Concept(CN)':
    - '数据库、数据湖、数据仓库、湖仓一体、智能湖仓': 'chap12/1aws_data_storage.md'
    
    
repo_url: https://github.com/Chao-Xi/jxawscbdbook.git
repo_name: "jxawscbdbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'amber'
    accent: 'amber'
  i18n:
    prev: 'Previous'
    next: 'Next'