site_name: Jacob AWS Certified Big Data Specialty Tutorial
site_description: "Jacob's AWS Certified Big Data Specialty"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Section1:Intro':
    - 'AWS Certified Big Data Specialty 2020 - In Depth & Hands On!': 'chap1/1intro.md'
  - 'Section2:Collection':
    - 'L1 Collections - Kinesis DataStream Overview': 'chap2/2Kinesis_data_collection.md'
    - 'L2 [Exercise] Kinesis Firehose (PurchaseLogs/OrderLogs)': 'chap2/3Coll_Kinesis_Firehose_Exer.md'
    - 'L3 [Exercise] Kinesis Data Streams': 'chap2/4Coll_Kinesis_DS_Exer.md'
    - 'L4 SQS vs. Kinesis Data Stream': 'chap2/5Coll_SQS_Kinesis.md'
  - 'Section3:Storage':
    - 'L1 Storage S3': 'chap3/8Storage_S3.md'
    - 'L2 DynamoDB Overview': 'chap3/9Storage_dynamoDB.md'
  - 'Section7:Security':
    - 'L1 Security - Encryption': 'chap7/32Secu_Encryption.md'
    - 'L2 AWS Services Security Deep Dive': 'chap7/33Secu_bg_svc.md'
    - 'L3 Account and Identity Federation': 'chap7/34Secu_account_fedration.md'
    - 'L4 Polices, CloudTrail & VPCe': 'chap7/35Secu_others.md'
  - 'Section8:WrapUp':
    - 'L1 AWS Bigdata Integration': 'chap8/36bg_integration.md'
    - 'L2 AWS Big Data Instances': 'chap8/37bg_instances.md'

repo_url: https://github.com/Chao-Xi/jxawscbdbook.git
repo_name: "jxawscbdbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'amber'
    accent: 'amber'
  i18n:
    prev: 'Previous'
    next: 'Next'