site_name: Jacob AWS Certified Big Data Specialty Tutorial
site_description: "Jacob's AWS Certified Big Data Specialty"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"

repo_url: https://github.com/Chao-Xi/jxawscbdbook.git
repo_name: "jxawscbdbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'amber'
    accent: 'amber'
  i18n:
    prev: 'Previous'
    next: 'Next'